### ISSUE TITLE
Request: Support JToken assertions

### ISSUE THREAD

**Issue by TotalTest** [VerifyTests/Verify.Assertions#2]
Hi Simon, is JToken supported here also? 

The below doesn't fail for me...

```
[Fact]
public async Task Test7()
{
    var dt = DateTime.Now.ToLongTimeString();

    var json = "{\"Name\": \"one\", \"Value\": \"val\", \"A\": \"the\",\"B\":\"yes\",\"C\":\"p\",\"Dt\":\"" + dt + "\"}";
    var res = JToken.Parse(json);

    var result = await Verify(res)
        .ScrubInlineDateTimes("T")
        .Assert<JToken>(a => Assert.Equal("thee", a["A"].ToString()));
}
```

**Comment by SimonCropp** [comment]
can u try Verify  26.1.6

**Comment by TotalTest** [comment]
I'm getting the below error:

![image](https://github.com/user-attachments/assets/cffc1e19-cca7-45de-aa8f-b37a1502a90d)

This isn't a showstopper so it can wait, also I think JObject would also need changes to be supported.

**Comment by SimonCropp** [comment]
there are many jtokens. your callback will be hit for all of them

![image](https://github.com/user-attachments/assets/413cd3c4-0a91-433a-b15a-3e56488e6ca4)

**Comment by TotalTest** [comment]
Hi, may need to revive this issue. I'm trying to the Assert with JObject (Argon namespace). But the action doesn't seem to get called at all...

```
using Argon;

[Fact]
public async Task Test7()
{
    var dt = DateTime.Now.ToLongTimeString();
    var json = "{\"Name\": \"one\", \"Value\": \"val\", \"A\": \"the\",\"B\":\"yes\",\"C\":\"p\",\"Dt\":\"" + dt + "\"}";
    var res = JObject.Parse(json);

    await Verify(res)
        .ScrubInlineDateTimes("T")
        .Assert<JObject>(a =>
        {
            var val = a["Name"].ToString();
            Assert.Equal(val, "onee");
        });
}

```

Let me know if I should raise a new issue.

**Comment by SimonCropp** [comment]
@TotalTest can u share a zipped stand alone repo?

**Comment by TotalTest** [comment]
Sure, I have attached a zip. The test 'Test1' should just pass. But line 25 doesn't seem to be hit.

<img width="1436" height="654" alt="Image" src="https://github.com/user-attachments/assets/923ea5a5-98a8-4bb7-9bd1-81d2d6c7efc0" />

[VerifyJObject.zip](https://github.com/user-attachments/files/27857315/VerifyJObject.zip)
