### ISSUE TITLE
Members are not scrubber when using ContractResolver in VerifySettings

### ISSUE THREAD

**Issue by TotalTest** [VerifyTests/Verify.Assertions#25]
I've noticed that if you supply VerifySettings when verifying, but set the ContractResolver - the members are not scrubbed.

![image](https://github.com/user-attachments/assets/795567eb-c55d-42f6-a9f9-caaf4308b2aa)

Result:

![image](https://github.com/user-attachments/assets/fc71776a-6b8e-44b0-8b3a-8f506f7d66ed)

Even without the camelcase option you will find the same.

To reproduce the below code can be used, **on the first run don't pass in the VerifySettings to get the scrubbed baseline**

```
using System.Runtime.CompilerServices;
using Argon;

namespace TestProject1
{
    [TestClass]
    public class UnitTest1 : VerifyBase
    {
        [ModuleInitializer]
        public static void Init() => VerifyAssertions.Initialize();

        [TestMethod]
        public async Task TestMethod1()
        {
            var rt = new RandomTest
            {
                Id = Guid.NewGuid(),
                Name = "TestName",
                Age = 20,
                Time = DateTime.Now
            };

            var settings = new VerifySettings();

            settings.AddExtraSettings(a =>
            {
                a.ContractResolver = new DefaultContractResolver
                {
                    NamingStrategy = new CamelCaseNamingStrategy()
                };
            });

            await Verify(rt, settings)
                .ScrubMember<RandomTest>(a => a.Name)
                .Assert<RandomTest>(obj =>
                {
                    Assert.AreEqual(obj.Name, "TestName");
                });
        }
    }

    public class RandomTest
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public DateTime Time { get; set; }
    }
}
```

**Comment by SimonCropp** [comment]
unfortunately ContractResolver is the API Verify uses to ply into Argon. so replacing it is not supported

**Comment by TotalTest** [comment]
Ok, is there a recommended way to camel case properties, or order them alphabetically for example. i.e. transform before Verifying.

**Comment by SimonCropp** [comment]
> order them alphabetically for example

https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#sortpropertiesalphabetically

> there a recommended way to camel case properties

not a recommended way. why do you want to do this?

but here is a hack that should work
```
    [ModuleInitializer]
    public static void Init() =>
        VerifierSettings.AddExtraSettings(_ =>
        {
            var resolver = (DefaultContractResolver)_.ContractResolver!;
            resolver.NamingStrategy = new CamelCaseNamingStrategy();
        });
```

**Comment by TotalTest** [comment]
This helps a lot thank you.
